name = "belyi"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Belyi"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "oka"
git = "https://github.com/lana-agents/oka.git"
rev = "da228a2cf9671aaba08ddc96274d75e098b28f67"

[[lean_lib]]
name = "Belyi"
