/-
Copyright (c) 2026 The Belyi project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Belyi project contributors
-/
import Belyi.CurveField.Fundamental
import Mathlib.RingTheory.DedekindDomain.Different

/-!
# Simple extensions of curve fields generated by an element with unit derivative

Let `L / K` be a finite extension of curve fields and let `A_t ⊆ B` be the chart ring of `K`
at a transcendental `t` and its integral closure in `L`
(`Belyi.CurveField.Place.chartRingExt`). If `L = K(x)` with `x ∈ B` and `g'(x)` is a unit at
a place `Q` of `L` over `P ∋ t`, where `g` is the minimal polynomial of `x` over `A_t`, then

* `Q` is unramified over `P`
  (`Belyi.CurveField.Place.ramificationIdx_eq_one_of_aeval_derivative`): the different of
  `B / A_t` contains `g'(x)`, and `𝔮 ^ (e - 1)` divides the different;
* the residue field of `Q` is generated over that of `P` by the residue of `x`
  (`Belyi.CurveField.QbarPoint.fieldOf_le_adjoin_of_aeval_derivative`, stated for algebraic
  points): the conductor of `A_t[x]` in `B` times the different is `(g'(x))`, so the
  conductor contains an element `c ∉ 𝔮`, and `c · B ⊆ A_t[x]`.

We also record general facts on towers: a finite extension of a curve field is a curve field
(`Belyi.CurveField.isCurveField_of_finite`), restriction of places and points is transitive,
and ramification indices are multiplicative (`Belyi.CurveField.Place.ramificationIdx_tower`).
-/

open IsLocalRing Module Polynomial IsDedekindDomain
open scoped IntermediateField

namespace Belyi.CurveField

/-- A finite extension of a curve field is a curve field. -/
theorem isCurveField_of_finite (K F : Type*) [Field K] [CharZero K] [IsCurveField K]
    [Field F] [CharZero F] [Algebra K F] [FiniteDimensional K F] : IsCurveField F := by
  obtain ⟨t, ht⟩ := exists_transcendental K
  have hb := (isTranscendenceBasis ht).algebraMap_comp (A := F)
  set s := algebraMap K F t
  have hs : Transcendental ℚ s := by
    have := hb.1.transcendental ()
    simpa using this
  have halg : Algebra.IsAlgebraic ℚ⟮s⟯ F := by
    have := hb.isAlgebraic_field
    rwa [Function.comp_def, Set.range_const] at this
  refine ⟨s, hs, ?_⟩
  obtain ⟨S0, hS0⟩ := exists_finset_adjoin_eq_top K
  obtain ⟨S1, hS1⟩ := IntermediateField.fg_top (F := K) (E := F)
  classical
  let S : Finset F := S0.image (algebraMap K F) ∪ S1
  have hK : ∀ c : K, algebraMap K F c ∈ IntermediateField.adjoin ℚ (S : Set F) := by
    intro c
    have hc : c ∈ IntermediateField.adjoin ℚ (S0 : Set K) := hS0 ▸ trivial
    have := (IntermediateField.mem_map (S := IntermediateField.adjoin ℚ (S0 : Set K))
      (f := IsScalarTower.toAlgHom ℚ K F)).mpr ⟨c, hc, rfl⟩
    rw [IntermediateField.adjoin_map] at this
    refine IntermediateField.adjoin.mono ℚ _ _ ?_ this
    rintro _ ⟨y, hy, rfl⟩
    exact Finset.mem_coe.mpr (Finset.mem_union_left _ (Finset.mem_image_of_mem _ hy))
  have hS : IntermediateField.adjoin ℚ (S : Set F) = ⊤ := by
    rw [eq_top_iff]
    intro x _
    let E : IntermediateField K F :=
      (IntermediateField.adjoin ℚ (S : Set F)).toSubfield.toIntermediateField hK
    have hle : IntermediateField.adjoin K (S1 : Set F) ≤ E := by
      rw [IntermediateField.adjoin_le_iff]
      intro y hy
      exact IntermediateField.subset_adjoin ℚ _ (by simp [S, hy])
    rw [hS1] at hle
    exact hle (IntermediateField.mem_top (x := x))
  have htop : IntermediateField.adjoin ℚ⟮s⟯ (S : Set F) = ⊤ := by
    rw [← IntermediateField.restrictScalars_eq_top_iff (K := ℚ), eq_top_iff, ← hS,
      IntermediateField.adjoin_le_iff]
    exact IntermediateField.subset_adjoin _ _
  have := IntermediateField.finiteDimensional_adjoin (K := ℚ⟮s⟯) (S := (S : Set F))
    (fun x _ ↦ (Algebra.IsAlgebraic.isAlgebraic x).isIntegral)
  rw [htop] at this
  exact IntermediateField.topEquiv.toLinearEquiv.finiteDimensional

section Tower

variable {K M L : Type*} [Field K] [Field M] [Field L] [Algebra K M] [Algebra M L] [Algebra K L]
  [IsScalarTower K M L] [Algebra.IsIntegral K M] [Algebra.IsIntegral M L]
  [Algebra.IsIntegral K L]

/-- Restriction of places is transitive in a tower `K ⊆ M ⊆ L`. -/
theorem Place.restrict_restrict (Q : Place L) : (Q.restrict M).restrict K = Q.restrict K := by
  ext x
  simp only [mem_restrict_iff, ← IsScalarTower.algebraMap_apply]

variable [CharZero K] [CharZero M] [CharZero L] [IsCurveField K] [IsCurveField M]
  [IsCurveField L]

/-- Multiplicativity of ramification indices in a tower `K ⊆ M ⊆ L`. -/
theorem Place.ramificationIdx_tower (Q : Place L) :
    Q.ramificationIdx K = Q.ramificationIdx M * (Q.restrict M).ramificationIdx K := by
  have h1 := Q.ord_algebraMap_eq_mul (K := K) (Q.restrict K).uniformizer
  rw [ord_uniformizer, mul_one, IsScalarTower.algebraMap_apply K M L,
    Q.ord_algebraMap_eq_mul (K := M), (Q.restrict M).ord_algebraMap_eq_mul (K := K),
    restrict_restrict, ord_uniformizer, mul_one] at h1
  exact_mod_cast h1.symm

omit [IsCurveField K] [IsCurveField M] [IsCurveField L] in
/-- Restriction of algebraic points is transitive in a tower `K ⊆ M ⊆ L`. -/
theorem QbarPoint.restrict_restrict (y : QbarPoint L) :
    (y.restrict M).restrict K = y.restrict K := by
  refine QbarPoint.ext' (Place.restrict_restrict y.P) fun a ↦ ?_
  have h1 := (y.restrict M).eval_restrict (K := K) a.1 a.2
  have h2 := y.eval_restrict (K := K) a.1 (by
    change algebraMap K L a.1 ∈ y.P.1
    rw [IsScalarTower.algebraMap_apply K M L]; exact a.2)
  change ((y.restrict M).restrict K).eval a.1 a.2 = (y.restrict K).eval a.1 _
  rw [h1, h2, (y.eval_restrict (K := M) _ _)]
  exact y.eval_congr (IsScalarTower.algebraMap_apply K M L a.1).symm _

end Tower

namespace Place

variable {K L : Type*} [Field K] [CharZero K] [IsCurveField K] [Field L] [CharZero L]
  [IsCurveField L] [Algebra K L] [FiniteDimensional K L]

section Core

variable (t : K) [Fact (Transcendental ℚ t)]

set_option synthInstance.maxHeartbeats 400000 in
-- instance search on `integralClosure (chartRing t) L` is slow
/-- Mathlib's ramification index of `w` over the prime of `A_t` below `P` is `e(Q|P)` for the
place `Q` of `L` at `w`. -/
theorem ramificationIdx'_eq_ramificationIdx (P : Place K)
    (htP : t ∈ P.1) (w : HeightOneSpectrum (chartRingExt K L t))
    [w.asIdeal.LiesOver (P.toChart t htP).asIdeal] :
    Ideal.ramificationIdx' (P.toChart t htP).asIdeal w.asIdeal =
      (ofHeightOne L w).ramificationIdx K := by
  have hPv : ofChart t (P.toChart t htP) = P := ofChart_toChart t P htP
  have hQ' : (ofHeightOne L w).restrict K = P := (restrict_ofHeightOne t _ w).trans hPv
  have h1 := valuation_liesOver' L (P.toChart t htP) w P.uniformizer
  have h2 : (ofHeightOne L w).ord (algebraMap K L P.uniformizer) =
      Ideal.ramificationIdx' (P.toChart t htP).asIdeal w.asIdeal := by
    rw [ord_ofHeightOne, ← h1, WithZero.log_pow, nsmul_eq_mul, ← mul_neg, ← ord_ofChart, hPv,
      ord_uniformizer, mul_one]
  have h3 := (ofHeightOne L w).ord_algebraMap_eq_mul (K := K) P.uniformizer
  rw [hQ', ord_uniformizer, mul_one, h2] at h3
  exact_mod_cast h3

set_option synthInstance.maxHeartbeats 400000 in
-- instance search on `integralClosure (chartRing t) L` is slow
omit [CharZero L] [IsCurveField L] in
/-- The prime of `A_t^L` below a place `Q` lies over the prime of `A_t` below `Q ∩ K`. -/
theorem liesOver_heightOneBelow (Q : Place L) (htQ : t ∈ (Q.restrict K).1) :
    (heightOneBelow (R := chartRingExt K L t) Q.1 Q.ne_top
      (algebraMap_chartRingExt_mem t Q htQ)).asIdeal.LiesOver
      ((Q.restrict K).toChart t htQ).asIdeal := by
  refine ⟨?_⟩
  ext r
  rw [Ideal.mem_comap, mem_heightOneBelow_chartRingExt_iff t Q htQ, mem_toChart_iff]
  exact Iff.rfl

set_option maxHeartbeats 800000 in
-- elaboration in `integralClosure (chartRing t) L` is slow
set_option synthInstance.maxHeartbeats 400000 in
-- instance search on `integralClosure (chartRing t) L` is slow
/-- If `L = K(x)` with `x ∈ A_t^L` and `g'(x)` is a unit at `Q` (`g` the minimal polynomial of
`x` over `A_t`), then `Q` is unramified over `Q ∩ K`. -/
theorem ramificationIdx_eq_one_of_aeval_derivative (x : chartRingExt K L t)
    (hx : Algebra.adjoin K {algebraMap (chartRingExt K L t) L x} = ⊤)
    (Q : Place L) (htQ : t ∈ (Q.restrict K).1)
    (hunit : algebraMap (chartRingExt K L t) L
      (aeval x (derivative (minpoly (chartRing t) x))) ∉ Q.1.nonunits) :
    Q.ramificationIdx K = 1 := by
  set w := heightOneBelow (R := chartRingExt K L t) Q.1 Q.ne_top
    (algebraMap_chartRingExt_mem t Q htQ)
  set v := (Q.restrict K).toChart t htQ
  haveI := liesOver_heightOneBelow t Q htQ
  haveI : v.asIdeal.IsMaximal := v.isMaximal
  have he := ramificationIdx'_eq_ramificationIdx t (Q.restrict K) htQ w
  rw [ofHeightOne_heightOneBelow] at he
  rw [← he]
  generalize hE : Ideal.ramificationIdx' v.asIdeal w.asIdeal = e at he
  have hpos : e ≠ 0 := by
    rw [he]; exact (Q.ramificationIdx_pos).ne'
  have hdvd : w.asIdeal ^ e ∣
      v.asIdeal.map (algebraMap (chartRing t) (chartRingExt K L t)) :=
    hE ▸ Ideal.dvd_iff_le.mpr Ideal.le_pow_ramificationIdx'
  have hdiff := pow_sub_one_dvd_differentIdeal_aux (chartRing t) K L w.asIdeal hpos v.ne_bot hdvd
  by_contra hne
  have h1 : w.asIdeal ∣ differentIdeal (chartRing t) (chartRingExt K L t) :=
    (dvd_pow_self _ (by omega)).trans hdiff
  have hmem := aeval_derivative_mem_differentIdeal (chartRing t) K L x hx
  exact hunit (mem_heightOneBelow.mp (Ideal.dvd_iff_le.mp h1 hmem))

set_option maxHeartbeats 800000 in
-- elaboration in `integralClosure (chartRing t) L` is slow
set_option synthInstance.maxHeartbeats 400000 in
-- instance search on `integralClosure (chartRing t) L` is slow
omit [CharZero L] [IsCurveField L] in
/-- If `L = K(x)` with `x ∈ A_t^L` and `g'(x)` is a unit at `Q`, then the conductor of `A_t[x]`
in `A_t^L` contains an element which is a unit at `Q`. -/
theorem exists_mem_conductor_notMem (x : chartRingExt K L t)
    (hx : Algebra.adjoin K {algebraMap (chartRingExt K L t) L x} = ⊤)
    (Q : Place L) (htQ : t ∈ (Q.restrict K).1)
    (hunit : algebraMap (chartRingExt K L t) L
      (aeval x (derivative (minpoly (chartRing t) x))) ∉ Q.1.nonunits) :
    ∃ c ∈ conductor (chartRing t) x, algebraMap (chartRingExt K L t) L c ∉ Q.1.nonunits := by
  have hcd := conductor_mul_differentIdeal (chartRing t) K L x hx
  by_contra h
  push Not at h
  have hle : conductor (chartRing t) x * differentIdeal (chartRing t) (chartRingExt K L t) ≤
      (heightOneBelow (R := chartRingExt K L t) Q.1 Q.ne_top
        (algebraMap_chartRingExt_mem t Q htQ)).asIdeal :=
    Ideal.mul_le_right.trans fun c hc ↦ mem_heightOneBelow.mpr (h c hc)
  rw [hcd] at hle
  exact hunit (mem_heightOneBelow.mp (hle (Ideal.mem_span_singleton_self _)))

end Core

end Place

namespace QbarPoint

variable {K L : Type*} [Field K] [CharZero K] [IsCurveField K] [Field L] [CharZero L]
  [IsCurveField L] [Algebra K L] [FiniteDimensional K L]

variable (t : K) [Fact (Transcendental ℚ t)]

set_option maxHeartbeats 800000 in
-- elaboration in `integralClosure (chartRing t) L` is slow
set_option synthInstance.maxHeartbeats 400000 in
-- instance search on `integralClosure (chartRing t) L` is slow
omit [IsCurveField L] in
/-- If `L = K(x)` with `x ∈ A_t^L` and `g'(x)` is a unit at `y`, then the field of definition of
`y` is generated over that of `y|_K` by `x(y)`. -/
theorem fieldOf_le_adjoin_of_aeval_derivative (x : Place.chartRingExt K L t)
    (hx : Algebra.adjoin K {algebraMap (Place.chartRingExt K L t) L x} = ⊤)
    (y : QbarPoint L) (htQ : t ∈ (y.P.restrict K).1)
    (hunit : algebraMap (Place.chartRingExt K L t) L
      (aeval x (derivative (minpoly (chartRing t) x))) ∉ y.P.1.nonunits) :
    y.fieldOf ≤ (IntermediateField.adjoin (y.restrict K).fieldOf
      {y.eval (algebraMap (Place.chartRingExt K L t) L x)
        (Place.algebraMap_chartRingExt_mem t y.P htQ x)}).restrictScalars ℚ := by
  have hB := Place.algebraMap_chartRingExt_mem t y.P htQ
  obtain ⟨c, hc, hcw⟩ := Place.exists_mem_conductor_notMem t x hx y.P htQ hunit
  -- values of elements of `A[x]` lie in the right-hand side
  have hev : ∀ r ∈ Algebra.adjoin (chartRing t) {x},
      y.eval (algebraMap (Place.chartRingExt K L t) L r) (hB r) ∈
        IntermediateField.adjoin (y.restrict K).fieldOf
          {y.eval (algebraMap (Place.chartRingExt K L t) L x) (hB x)} := by
    intro r hr
    induction hr using Algebra.adjoin_induction with
    | mem r hr =>
      obtain rfl := Set.mem_singleton_iff.mp hr
      exact IntermediateField.subset_adjoin _ _ (Set.mem_singleton _)
    | algebraMap a =>
      have hmem : algebraMap (chartRing t) K a ∈ (y.restrict K).P.1 :=
        (y.P.restrict K).algebraMap_chartRing_mem t htQ a
      have h1 := y.eval_restrict (algebraMap (chartRing t) K a) hmem
      have h2 : algebraMap (Place.chartRingExt K L t) L
          (algebraMap (chartRing t) (Place.chartRingExt K L t) a) =
          algebraMap K L (algebraMap (chartRing t) K a) := rfl
      rw [y.eval_congr h2, ← h1]
      exact IntermediateField.algebraMap_mem _
        (⟨_, (y.restrict K).eval_mem_fieldOf hmem⟩ : (y.restrict K).fieldOf)
    | add r s _ _ hr hs =>
      rw [y.eval_congr (map_add _ r s), y.eval_add (hB r) (hB s)]
      exact add_mem hr hs
    | mul r s _ _ hr hs =>
      rw [y.eval_congr (map_mul _ r s), y.eval_mul (hB r) (hB s)]
      exact mul_mem hr hs
  rintro _ ⟨r0, rfl⟩
  obtain ⟨b, rfl⟩ :=
    CurveField.residue_comp_surjective (R := Place.chartRingExt K L t) y.P.1 y.P.ne_top hB r0
  change y.eval (algebraMap (Place.chartRingExt K L t) L b) (hB b) ∈ _
  have hc0 : y.eval (algebraMap (Place.chartRingExt K L t) L c) (hB c) ≠ 0 := by
    exact fun h ↦ hcw (ValuationSubring.coe_mem_nonunits_iff.mpr
      ((y.eval_eq_zero_iff_mem_maximalIdeal (hB c)).mp h))
  have hcb := hev _ ((mem_conductor_iff.mp hc) b)
  have hcc := hev _ (by simpa using (mem_conductor_iff.mp hc) 1)
  rw [y.eval_congr (map_mul _ c b), y.eval_mul (hB c) (hB b)] at hcb
  have := div_mem hcb hcc
  rwa [mul_div_cancel_left₀ _ hc0] at this

end QbarPoint

section KummerStep
variable {K L : Type*} [Field K] [CharZero K] [IsCurveField K] [Field L] [CharZero L]
  [IsCurveField L] [Algebra K L] [FiniteDimensional K L]

namespace Place

/-- For `a ∈ O_P` there is a chart `A_t` with `t ∈ O_P` and `a ∈ A_t`. -/
theorem exists_chart_mem (P : Place K) {a : K} (ha : a ∈ P.1) :
    ∃ t : K, Transcendental ℚ t ∧ t ∈ P.1 ∧ a ∈ chartRing t := by
  by_cases hta : Transcendental ℚ a
  · exact ⟨a, hta, ha, self_mem_chartRing a⟩
  · obtain ⟨t, ht, htP⟩ := P.exists_transcendental_mem
    refine ⟨t, ht, htP, ?_⟩
    have : IsIntegral ℚ a := (not_not.mp hta).isIntegral
    exact this.tower_top

variable {w : L} {a : K} {N : ℕ}

/-- If `w ^ N = a` with `ord_P a = 0`, then `w` is regular at every `Q` over `P`, and either
`w = 0` or `ord_Q w = 0`. -/
theorem mem_of_pow_eq (hN : 0 < N) (hw : w ^ N = algebraMap K L a) (Q : Place L)
    (ha : (Q.restrict K).ord a = 0) : w ∈ Q.1 ∧ (w = 0 ∨ Q.ord w = 0) := by
  rcases eq_or_ne w 0 with rfl | hw0
  · exact ⟨Q.1.zero_mem, Or.inl rfl⟩
  have h := Q.ord_algebraMap_eq_mul (K := K) a
  rw [← hw, ord_pow, ha, mul_zero] at h
  have h0 : Q.ord w = 0 := by
    rcases mul_eq_zero.mp h with h | h
    · exact absurd h (by exact_mod_cast hN.ne')
    · exact h
  exact ⟨Q.mem_of_ord_nonneg h0.ge, Or.inr h0⟩

set_option maxHeartbeats 800000 in
-- elaboration in `integralClosure (chartRing t) L` is slow
set_option synthInstance.maxHeartbeats 400000 in
-- instance search on `integralClosure (chartRing t) L` is slow
/-- The Kummer generator `w` (with `w ^ N = a`, `a` a unit or zero at `P`) is an element of
some `A_t^L` whose minimal polynomial over `A_t` has derivative a unit at `Q`. -/
theorem exists_chart_aeval_derivative (hN : 0 < N) (hw : w ^ N = algebraMap K L a)
    (Q : Place L) (ha : (Q.restrict K).ord a = 0) :
    ∃ (t : K) (_ : Fact (Transcendental ℚ t)) (_ : t ∈ (Q.restrict K).1)
      (x : chartRingExt K L t), algebraMap (chartRingExt K L t) L x = w ∧
      algebraMap (chartRingExt K L t) L
        (aeval x (derivative (minpoly (chartRing t) x))) ∉ Q.1.nonunits := by
  have haP : a ∈ (Q.restrict K).1 := by
    rcases eq_or_ne a 0 with rfl | ha0
    · exact (Q.restrict K).1.zero_mem
    · exact (Q.restrict K).mem_of_ord_nonneg ha.ge
  obtain ⟨t, ht, htQ, hat⟩ := (Q.restrict K).exists_chart_mem haP
  haveI : Fact (Transcendental ℚ t) := ⟨ht⟩
  obtain ⟨a', ha'⟩ : ∃ a' : chartRing t, algebraMap (chartRing t) L a' = algebraMap K L a :=
    ⟨⟨a, hat⟩, rfl⟩
  have hp : aeval w (X ^ N - C a') = 0 := by
    simp only [aeval_sub, aeval_X_pow, aeval_C]
    rw [ha', hw, sub_self]
  have hint : IsIntegral (chartRing t) w :=
    ⟨X ^ N - C a', monic_X_pow_sub_C a' hN.ne', hp⟩
  obtain ⟨x, hxw⟩ : ∃ x : chartRingExt K L t, algebraMap (chartRingExt K L t) L x = w :=
    ⟨⟨w, hint⟩, rfl⟩
  have hinj := FaithfulSMul.algebraMap_injective (chartRingExt K L t) L
  have hinjA : Function.Injective (algebraMap (chartRing t) (chartRingExt K L t)) := by
    intro b c hbc
    have := congrArg (algebraMap (chartRingExt K L t) L) hbc
    exact Subtype.ext ((algebraMap K L).injective this)
  refine ⟨t, inferInstance, htQ, x, hxw, ?_⟩
  rcases eq_or_ne w 0 with hw0 | hw0'
  · -- `w = 0`: the minimal polynomial is `X`
    have hx0 : x = 0 := hinj (by rw [hxw, hw0, map_zero])
    have hm : minpoly (chartRing t) (0 : chartRingExt K L t) = X - C 0 := by
      have := minpoly.eq_X_sub_C_of_algebraMap_inj (A := chartRing t)
        (B := chartRingExt K L t) 0 hinjA
      rwa [map_zero] at this
    rw [hx0, hm, derivative_sub, derivative_X, derivative_C, sub_zero, map_one, map_one]
    rw [ValuationSubring.mem_nonunits_iff, map_one]
    exact lt_irrefl 1
  have hwu : Q.ord w = 0 := ((mem_of_pow_eq hN hw Q ha).2.resolve_left hw0')
  have hxint : IsIntegral (chartRing t) x := IsIntegralClosure.isIntegral (chartRing t) L x
  have hpx : aeval x (X ^ N - C a') = 0 := by
    apply hinj
    rw [← aeval_algebraMap_apply, hxw, hp, map_zero]
  haveI : IsIntegrallyClosed (chartRing t) := inferInstance
  haveI : IsDomain (chartRingExt K L t) := inferInstance
  haveI : Module.IsTorsionFree (chartRing t) (chartRingExt K L t) := inferInstance
  obtain ⟨h, hh⟩ := minpoly.isIntegrallyClosed_dvd (R := chartRing t) (S := chartRingExt K L t)
    hxint hpx
  have h1 : aeval x (derivative (X ^ N - C a')) = (N : chartRingExt K L t) * x ^ (N - 1) := by
    rw [derivative_sub, derivative_C, sub_zero, derivative_X_pow, map_mul, aeval_C, aeval_X_pow,
      map_natCast]
  have h2 : aeval x (derivative (minpoly (chartRing t) x * h)) =
      aeval x (derivative (minpoly (chartRing t) x)) * aeval x h := by
    rw [derivative_mul, map_add, map_mul, map_mul, minpoly.aeval (chartRing t) x, zero_mul,
      add_zero]
  rw [hh, h2] at h1
  have hL := congrArg (algebraMap (chartRingExt K L t) L) h1
  rw [map_mul, map_mul, map_natCast, map_pow, hxw] at hL
  have hH := algebraMap_chartRingExt_mem t Q htQ (aeval x h)
  set G := algebraMap (chartRingExt K L t) L (aeval x (derivative (minpoly (chartRing t) x)))
  set H := algebraMap (chartRingExt K L t) L (aeval x h)
  have hne : (N : L) * w ^ (N - 1) ≠ 0 :=
    mul_ne_zero (Nat.cast_ne_zero.mpr hN.ne') (pow_ne_zero _ hw0')
  have hord : Q.ord ((N : L) * w ^ (N - 1)) = 0 := by
    rw [Q.ord_mul (Nat.cast_ne_zero.mpr hN.ne') (pow_ne_zero _ hw0'), ord_natCast, ord_pow, hwu]
    simp
  intro hG
  rw [← hL] at hne hord
  have hG0 : G ≠ 0 := fun h0 ↦ hne (by rw [h0, zero_mul])
  have hH0 : H ≠ 0 := fun h0 ↦ hne (by rw [h0, mul_zero])
  have hGpos : 0 < Q.ord G := (Q.ord_pos_iff).mpr ⟨hG0, hG⟩
  have hHnn : 0 ≤ Q.ord H := Q.ord_nonneg_of_mem hH
  rw [Q.ord_mul hG0 hH0] at hord
  omega

omit [CharZero K] [IsCurveField K] [CharZero L] [IsCurveField L] in
/-- `K(w) = L` as fields implies `K[w] = L` (`L / K` is algebraic). -/
theorem algebra_adjoin_eq_top_of_adjoin_eq_top (hgen : K⟮w⟯ = ⊤) :
    Algebra.adjoin K {w} = ⊤ := by
  have := IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
    (Algebra.IsAlgebraic.isAlgebraic (R := K) w)
  rw [hgen, IntermediateField.top_toSubalgebra] at this
  exact this.symm

/-- **Kummer extensions are unramified at units.** If `L = K(w)` with `w ^ N = a` and `a` is a
unit (or zero) at `P = Q ∩ K`, then `e(Q|P) = 1`. -/
theorem ramificationIdx_eq_one_of_pow_eq (hN : 0 < N) (hw : w ^ N = algebraMap K L a)
    (hgen : K⟮w⟯ = ⊤) (Q : Place L) (ha : (Q.restrict K).ord a = 0) :
    Q.ramificationIdx K = 1 := by
  obtain ⟨t, _, htQ, x, hxw, hunit⟩ := exists_chart_aeval_derivative hN hw Q ha
  refine ramificationIdx_eq_one_of_aeval_derivative t x ?_ Q htQ hunit
  rw [hxw]
  exact algebra_adjoin_eq_top_of_adjoin_eq_top hgen

end Place

namespace QbarPoint

variable {w : L} {a : K} {N : ℕ}

/-- **Residue fields of Kummer extensions.** If `L = K(w)` with `w ^ N = a` and `a` is a unit
(or zero) at the image of the point `y`, then `ℚ(y) = ℚ(y|_K)(w(y))`. -/
theorem fieldOf_eq_adjoin_of_pow_eq (hN : 0 < N) (hw : w ^ N = algebraMap K L a)
    (hgen : K⟮w⟯ = ⊤) (y : QbarPoint L) (ha : (y.P.restrict K).ord a = 0) :
    y.fieldOf = (IntermediateField.adjoin (y.restrict K).fieldOf
      {y.eval w (Place.mem_of_pow_eq hN hw y.P ha).1}).restrictScalars ℚ := by
  refine le_antisymm ?_ ?_
  · obtain ⟨t, _, htQ, x, hxw, hunit⟩ := Place.exists_chart_aeval_derivative hN hw y.P ha
    have h := fieldOf_le_adjoin_of_aeval_derivative t x
      (by rw [hxw]; exact Place.algebra_adjoin_eq_top_of_adjoin_eq_top hgen) y htQ hunit
    rwa [y.eval_congr hxw] at h
  · intro z hz
    have hle : IntermediateField.adjoin (y.restrict K).fieldOf
        {y.eval w (Place.mem_of_pow_eq hN hw y.P ha).1} ≤
          IntermediateField.extendScalars y.fieldOf_restrict_le := by
      rw [IntermediateField.adjoin_le_iff, Set.singleton_subset_iff]
      exact y.eval_mem_fieldOf _
    exact hle hz

end QbarPoint

end KummerStep

end Belyi.CurveField
