/-
Copyright (c) 2026 The Belyi project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Belyi project contributors
-/
import Belyi.RigidityGroupTheory
import Mathlib.Topology.Algebra.ContinuousMonoidHom
import Mathlib.Topology.Algebra.Group.Quotient
import Mathlib.Topology.Algebra.OpenSubgroup
import Mathlib.Topology.LocallyConstant.Basic

/-!
# Finitely many bounded-index open subgroups of a topologically finitely generated group

This file is the **topological / profinite analogue** of `Belyi/RigidityGroupTheory.lean`.
It is piece (1) of the survey-scoped reduction of the rigidity input **B9** (taxis issue
**#211**, parent **#210**): the abstract engine that, via the étale-`π₁` Galois-category
framework of `chrisflav/pi1`, feeds the finiteness of bounded-degree Belyi covers.

Where `Belyi/RigidityGroupTheory.lean` shows a *discretely* finitely generated group has
finitely many subgroups of bounded index, here we show:

* `Belyi.finite_continuousMonoidHom_of_topFG`: for a **topologically finitely generated**
  topological group `G` and a finite discrete group `N`, there are only finitely many
  **continuous** homomorphisms `G →ₜ* N`. (A continuous hom is determined by its values on
  a finite topologically-generating set, because two continuous homs agreeing on a dense
  subgroup agree everywhere.)
* `Belyi.finite_openSubgroup_index_le`: consequently, `G` has only finitely many **open**
  subgroups of index `≤ d`.

The étale fundamental group `Aut F` of a connected scheme (mathlib
`CategoryTheory/Galois/Topology.lean`: it is a profinite — hence compact Hausdorff — group)
is exactly such a `G`, so when it is topologically finitely generated (the Riemann-existence
input, tracked separately) these lemmas count its bounded-index open subgroups, i.e. its
bounded-degree finite étale covers.

## Main definitions and results

* `Belyi.TopologicallyFinitelyGenerated G`: a finite subset generates a dense subgroup.
* `Belyi.finite_continuousMonoidHom_of_topFG`.
* `Belyi.finite_openSubgroup_index_le`.

## References

* `references/rigidity-design.md` (label **B9**); the discrete analogue
  `Belyi/RigidityGroupTheory.lean`; taxis **#210**/#211 survey.
-/

namespace Belyi

open scoped Topology

/-- A topological group is **topologically finitely generated** if some finite subset
generates a dense subgroup. For a profinite group this is the usual notion. -/
def TopologicallyFinitelyGenerated (G : Type*) [Group G] [TopologicalSpace G] : Prop :=
  ∃ S : Finset G, Dense ((Subgroup.closure (S : Set G) : Subgroup G) : Set G)

/-- Two continuous homomorphisms into a discrete group that agree on a set `S` agree on the
subgroup generated by `S`. (Purely algebraic; continuity is not used.) -/
theorem eqOn_closure_of_eqOn_generators {G N : Type*} [Group G] [Group N]
    {φ ψ : G →* N} {S : Set G} (h : Set.EqOn (φ : G → N) ψ S) :
    ∀ x ∈ Subgroup.closure S, φ x = ψ x := by
  intro x hx
  induction hx using Subgroup.closure_induction with
  | mem y hy => exact h hy
  | one => simp
  | mul a b _ _ ha hb => rw [map_mul, map_mul, ha, hb]
  | inv a _ ha => rw [map_inv, map_inv, ha]

/-- **Core finiteness lemma.** For a topologically finitely generated topological group `G`
and a finite *discrete* group `N`, there are only finitely many continuous homomorphisms
`G →ₜ* N`: such a homomorphism is determined by its values on a finite topologically
generating set `S`, because two continuous homomorphisms agreeing on the dense subgroup
`⟨S⟩` agree everywhere (`N` is Hausdorff). -/
theorem finite_continuousMonoidHom_of_topFG {G N : Type*} [Group G] [TopologicalSpace G]
    [Group N] [TopologicalSpace N] [DiscreteTopology N] [Finite N]
    (hG : TopologicallyFinitelyGenerated G) :
    Finite (ContinuousMonoidHom G N) := by
  obtain ⟨S, hS⟩ := hG
  refine Finite.of_injective
    (fun (φ : ContinuousMonoidHom G N) => (fun (s : S) => φ (s : G))) ?_
  intro φ ψ h
  have hgen : Set.EqOn ((φ : G →* N) : G → N) (ψ : G →* N) (S : Set G) := by
    intro s hs
    exact congrFun h ⟨s, Finset.mem_coe.mp hs⟩
  have hcl : Set.EqOn ((φ : G →* N) : G → N) (ψ : G →* N)
      ((Subgroup.closure (S : Set G) : Subgroup G) : Set G) :=
    fun x hx => eqOn_closure_of_eqOn_generators hgen x hx
  have hfun : ((φ : G →* N) : G → N) = ((ψ : G →* N) : G → N) :=
    Continuous.ext_on hS φ.continuous ψ.continuous hcl
  ext x
  exact congrFun hfun x

section OpenSubgroup

-- Finite permutation groups carry the discrete topology, locally within this file.
local instance discreteTopologyPerm (X : Type*) [Finite X] :
    TopologicalSpace (Equiv.Perm X) := ⊥

local instance (X : Type*) [Finite X] : DiscreteTopology (Equiv.Perm X) := ⟨rfl⟩

/-- The coset permutation homomorphism `G →* Equiv.Perm X` of a continuous group action on a
finite discrete set `X` is continuous: each fibre is a finite intersection of the open sets
`{g | g • x = σ x}`, so the map is locally constant. -/
theorem continuous_toPermHom {G X : Type*} [Group G] [TopologicalSpace G] [MulAction G X]
    [TopologicalSpace X] [ContinuousSMul G X] [DiscreteTopology X] [Finite X] :
    Continuous (MulAction.toPermHom G X) := by
  apply IsLocallyConstant.continuous
  rw [IsLocallyConstant.iff_isOpen_fiber]
  intro σ
  have hset : (MulAction.toPermHom G X) ⁻¹' {σ}
      = ⋂ x : X, (fun g : G => g • x) ⁻¹' {σ x} := by
    ext g
    simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_iInter]
    constructor
    · intro hg x
      have hx : (MulAction.toPermHom G X) g x = σ x := by rw [hg]
      rwa [MulAction.toPermHom_apply, MulAction.toPerm_apply] at hx
    · intro hg
      ext x
      rw [MulAction.toPermHom_apply, MulAction.toPerm_apply]
      exact hg x
  rw [hset]
  refine isOpen_iInter_of_finite (fun x => ?_)
  exact (continuous_id.smul continuous_const).isOpen_preimage _ (isOpen_discrete _)

/-- The coset permutation homomorphism, transported along a bijection `e : X ≃ Y` to
`Equiv.Perm Y`, is continuous (`permCongrHom e` is continuous because its domain `Perm X`
is discrete). -/
theorem continuous_permCongrHom_comp_toPermHom {G X Y : Type*} [Group G] [TopologicalSpace G]
    [MulAction G X] [TopologicalSpace X] [ContinuousSMul G X] [DiscreteTopology X] [Finite X]
    [Finite Y] (e : X ≃ Y) :
    Continuous ⇑((permCongrHom e).comp (MulAction.toPermHom G X)) := by
  rw [MonoidHom.coe_comp]
  exact continuous_of_discreteTopology.comp continuous_toPermHom

/-- The continuous coset-action invariant assigned to an open subgroup `H` of index `≤ d`:
its index (as an element of `Fin (d+1)`), the coset action transported to a **continuous**
homomorphism `G →ₜ* Equiv.Perm (Fin H.index)`, and the base point. Mirrors
`Belyi.boundedIndexInvariant`, upgraded to record continuity. -/
noncomputable def openBoundedIndexInvariant (G : Type*) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] (d : ℕ)
    (H : {H : Subgroup G // IsOpen (H : Set G) ∧ H.index ≤ d ∧ H.index ≠ 0}) :
    Σ n : Fin (d + 1), ContinuousMonoidHom G (Equiv.Perm (Fin (n : ℕ))) × Fin (n : ℕ) :=
  haveI : Finite (G ⧸ H.1) := Subgroup.index_ne_zero_iff_finite.mp H.2.2.2
  haveI : DiscreteTopology (G ⧸ H.1) := QuotientGroup.discreteTopology H.2.1
  let e : G ⧸ H.1 ≃ Fin H.1.index := Finite.equivFinOfCardEq (α := G ⧸ H.1) (n := H.1.index) rfl
  ⟨⟨H.1.index, Nat.lt_succ_of_le H.2.2.1⟩,
    { toMonoidHom := (permCongrHom e).comp (MulAction.toPermHom G (G ⧸ H.1))
      continuous_toFun := continuous_permCongrHom_comp_toPermHom e },
    e ((1 : G) : G ⧸ H.1)⟩

/-- The subgroup `H` is recovered from its continuous invariant as a point stabilizer; hence
the invariant is injective. -/
theorem openBoundedIndexInvariant_recover (G : Type*) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] (d : ℕ)
    (H : {H : Subgroup G // IsOpen (H : Set G) ∧ H.index ≤ d ∧ H.index ≠ 0}) :
    stabOfHom (openBoundedIndexInvariant G d H).2.1.toMonoidHom
      (openBoundedIndexInvariant G d H).2.2 = H.1 := by
  haveI : Finite (G ⧸ H.1) := Subgroup.index_ne_zero_iff_finite.mp H.2.2.2
  exact stabOfHom_permCongrHom H.1 (Finite.equivFinOfCardEq (α := G ⧸ H.1) (n := H.1.index) rfl)

/-- **Bounded-index open subgroups are finite.** A topologically finitely generated
topological group has only finitely many open subgroups of index `≤ d`. This is the
profinite analogue of `Belyi.finite_boundedIndex_subgroups`; via the étale-`π₁`
Galois-category framework it counts the degree-`≤ d` finite étale covers of a connected
scheme with topologically finitely generated fundamental group. -/
theorem finite_openSubgroup_index_le (G : Type*) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] (hG : TopologicallyFinitelyGenerated G) (d : ℕ) :
    {H : Subgroup G | IsOpen (H : Set G) ∧ H.index ≤ d ∧ H.index ≠ 0}.Finite := by
  haveI : ∀ n : Fin (d + 1), Finite (ContinuousMonoidHom G (Equiv.Perm (Fin (n : ℕ)))) :=
    fun _ => finite_continuousMonoidHom_of_topFG hG
  rw [← Set.finite_coe_iff]
  refine Finite.of_injective (openBoundedIndexInvariant G d) ?_
  intro a b hab
  apply Subtype.ext
  rw [← openBoundedIndexInvariant_recover G d a, ← openBoundedIndexInvariant_recover G d b, hab]

end OpenSubgroup

end Belyi
