/-
Copyright (c) 2026 The Belyi project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Belyi project contributors
-/
import Belyi.P1
import Belyi.Definable
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
import Mathlib.Algebra.MvPolynomial.Division

/-!
# The projective line and change of base ring

First steps towards the canonical identification `ℙ¹_{k₀} ×_{k₀} K ≅ ℙ¹_K` required by
the pair version of B3 (taxis issue #48): this file constructs the comparison morphism

`Belyi.P1.mapOfAlgebra : P1 K ⟶ P1 k₀`

induced by the coefficient map `k₀[X₀,X₁] → K[X₀,X₁]` (a graded ring homomorphism),
shows that it commutes with the structure morphisms, and packages it as the canonical
morphism into the base change

`Belyi.P1.toPullback : P1 K ⟶ pullback (P1 k₀ ↘ Spec k₀) (specAlgebraMap k₀ K)`.

That `toPullback` is an isomorphism is the remaining content of the identification; it
is a chart-by-chart computation (`Away 𝒜 (X i) ⊗_{k₀} K ≅ Away ℬ (X i)`) and is left to
follow-up work.

## Main definitions

* `Belyi.P1.gradedMapOfAlgebra`: the coefficient map as a graded ring homomorphism.
* `Belyi.P1.mapOfAlgebra`: the induced morphism `P1 K ⟶ P1 k₀`.
* `Belyi.P1.toPullback`: the comparison morphism into the base change of `P1 k₀`.
-/

universe u

namespace Belyi.P1

open AlgebraicGeometry CategoryTheory Limits MvPolynomial ProjectiveSpectrum

attribute [local instance] MvPolynomial.gradedAlgebra

variable (k₀ K : Type u) [CommRing k₀] [CommRing K] [Algebra k₀ K]

/-- The coefficient map `k₀[X₀,X₁] → K[X₀,X₁]` as a graded ring homomorphism for the
standard gradings. -/
noncomputable def gradedMapOfAlgebra : P1Grading k₀ →+*ᵍ P1Grading K where
  __ := MvPolynomial.map (algebraMap k₀ K)
  map_mem hx := (mem_homogeneousSubmodule _ _).mpr
    (((mem_homogeneousSubmodule _ _).mp hx).map _)

@[simp]
lemma gradedMapOfAlgebra_apply (p : MvPolynomial (Fin 2) k₀) :
    gradedMapOfAlgebra k₀ K p = MvPolynomial.map (algebraMap k₀ K) p := rfl

/-- The irrelevant ideal of `K[X₀,X₁]` is generated by the images of the coordinates,
hence contained in the ideal generated by the image of the irrelevant ideal of
`k₀[X₀,X₁]`. This is the hypothesis needed to apply `Proj.map`. -/
lemma irrelevant_le_map_gradedMapOfAlgebra :
    HomogeneousIdeal.irrelevant (P1Grading K) ≤
      HomogeneousIdeal.map (gradedMapOfAlgebra k₀ K)
        (HomogeneousIdeal.irrelevant (P1Grading k₀)) := by
  classical
  rw [← toIdeal_le_toIdeal_iff, HomogeneousIdeal.toIdeal_irrelevant_le]
  intro i hi p hp
  -- `p` is homogeneous of positive degree `i`, so every monomial of `p` uses some variable
  have hph : p.IsHomogeneous i := (mem_homogeneousSubmodule _ _).mp hp
  change p ∈ (HomogeneousIdeal.map (gradedMapOfAlgebra k₀ K)
    (HomogeneousIdeal.irrelevant (P1Grading k₀))).toIdeal
  rw [p.as_sum]
  refine Ideal.sum_mem _ fun d hd => ?_
  have hd0 : d ≠ 0 := by
    rintro rfl
    exact absurd (hph (mem_support_iff.mp hd)) (by simpa using hi.ne)
  obtain ⟨j, hj⟩ : ∃ j, d j ≠ 0 := by
    by_contra h
    exact hd0 (by ext j; simpa using not_not.mp (not_exists.mp h j))
  -- the coordinate `X j` lies in the image ideal, and divides the monomial
  have hXj : (X j : MvPolynomial (Fin 2) k₀) ∈
      HomogeneousIdeal.irrelevant (P1Grading k₀) :=
    HomogeneousIdeal.mem_irrelevant_of_mem _ one_pos
      ((mem_homogeneousSubmodule _ _).mpr (isHomogeneous_X k₀ j))
  have hmemX : (X j : MvPolynomial (Fin 2) K) ∈
      (HomogeneousIdeal.map (gradedMapOfAlgebra k₀ K)
        (HomogeneousIdeal.irrelevant (P1Grading k₀))).toIdeal := by
    have h := Ideal.mem_map_of_mem (f := gradedMapOfAlgebra k₀ K)
      (show X j ∈ (HomogeneousIdeal.irrelevant (P1Grading k₀)).toIdeal from hXj)
    rwa [gradedMapOfAlgebra_apply, MvPolynomial.map_X] at h
  have hdvd : (X j : MvPolynomial (Fin 2) K) ∣ monomial d (coeff d p) := by
    rw [X, MvPolynomial.monomial_dvd_monomial]
    exact ⟨Or.inr (by simpa [Finsupp.single_le_iff] using Nat.one_le_iff_ne_zero.mpr hj),
      one_dvd _⟩
  exact Ideal.mem_of_dvd _ hdvd hmemX

/-- The morphism `ℙ¹_K ⟶ ℙ¹_{k₀}` induced by the base ring extension. -/
noncomputable def mapOfAlgebra : P1 K ⟶ P1 k₀ :=
  Proj.map (gradedMapOfAlgebra k₀ K) (irrelevant_le_map_gradedMapOfAlgebra k₀ K)

/-- The comparison morphism from `ℙ¹_K` to the base change of `ℙ¹_{k₀}` along
`Spec K ⟶ Spec k₀`. Showing that this is an isomorphism is the remaining content of the
canonical identification `ℙ¹_{k₀} ×_{k₀} K ≅ ℙ¹_K` (taxis issue #48). -/
noncomputable def toPullback
    (h : mapOfAlgebra k₀ K ≫ (P1 k₀ ↘ Spec (CommRingCat.of k₀)) =
      (P1 K ↘ Spec (CommRingCat.of K)) ≫ specAlgebraMap k₀ K) :
    P1 K ⟶ pullback (P1 k₀ ↘ Spec (CommRingCat.of k₀)) (specAlgebraMap k₀ K) :=
  pullback.lift (mapOfAlgebra k₀ K) (P1 K ↘ Spec (CommRingCat.of K)) h

@[reassoc (attr := simp)]
lemma toPullback_snd (h) :
    toPullback k₀ K h ≫ pullback.snd _ _ = (P1 K ↘ Spec (CommRingCat.of K)) :=
  pullback.lift_snd _ _ _

@[reassoc (attr := simp)]
lemma toPullback_fst (h) :
    toPullback k₀ K h ≫ pullback.fst _ _ = mapOfAlgebra k₀ K :=
  pullback.lift_fst _ _ _

end Belyi.P1
